name: "Setup Vite+"
description: "Install Vite+ (vp) and optionally cache project dependencies"
author: "voidzero-dev"
branding:
  icon: zap
  color: purple

inputs:
  version:
    description: "Version of Vite+ to install"
    required: false
    default: "latest"
  run-install:
    description: "Run `vp install` after setup. Accepts boolean or YAML object with cwd/args."
    required: false
    default: "true"
  node-version:
    description: "Node.js version to install via `vp env use`. If not specified, uses the default version bundled with Vite+."
    required: false
  cache:
    description: "Enable caching of project dependencies"
    required: false
    default: "false"
  cache-dependency-path:
    description: "Path to lock file for cache key generation. Auto-detected if not specified."
    required: false

outputs:
  version:
    description: "The installed version of Vite+"
  cache-hit:
    description: "Boolean indicating if cache was restored"

runs:
  using: node20
  main: dist/index.mjs
  post: dist/index.mjs
  post-if: success()
