name: 'Setup Vite+'
description: 'Install Vite+ (vite-plus-cli) and optionally cache project dependencies'
author: 'voidzero-dev'
branding:
  icon: zap
  color: purple

inputs:
  version:
    description: 'Version of vite-plus-cli to install'
    required: false
    default: 'latest'
  run-install:
    description: 'Run `vite install` after setup. Accepts boolean or YAML object with cwd/args.'
    required: false
    default: 'true'
  cache:
    description: 'Enable caching of project dependencies'
    required: false
    default: 'false'
  cache-dependency-path:
    description: 'Path to lock file for cache key generation. Auto-detected if not specified.'
    required: false

outputs:
  version:
    description: 'The installed version of vite-plus-cli'
  cache-hit:
    description: 'Boolean indicating if cache was restored'

runs:
  using: node20
  main: dist/index.mjs
  post: dist/index.mjs
  post-if: success()
